### PR TITLE
GQL: fix wrong block reward

### LINKED ISSUE #1390: Wrong reward in GQL
**Describe the bug**
Reward shown in GQL endpoint is missing the distribution reward, so it's just the sum of fee paid

**To Reproduce**
GQL query the current devnet
```
  blocks(hash: "a85bcbfbc157ead5922961a6d751c01ef455ee45d90aebfd44dc047e78af5d31") {
    header {
      reward
      feespaid
      height
      timestamp
      step
    }
  }
  ```

**Expected behaviour**
Reward should be the sum of every tx's fee + emission amount 

**Logs/Screenshot**
```json

    "blocks": [
      {
        "header": {
          "feespaid": 723145951,
          "height": 8667,
          "reward": 723145951,
          "step": 3,
          "timestamp": "2022-05-06 10:56:45 +0000 UTC"
        }
      }
    ],
```

**Platform**
N/A

**Additional context**
The reward resolver has not been updated after the removal of the distribute transaction

### PR DESCRIPTION
**Pull request by herr-seppia**
Resolves #1390

### CODE REVIEW

File: pkg/gql/query/blocks.go [hunk 1]
```diff
@@ -199,7 +224,7 @@ func resolveReward(p graphql.ResolveParams) (interface{}, error) {
 			return nil, errors.New("context does not store database conn")
 		}
 
-		reward := uint64(0)
+		reward := emissionAmount(b.Height)
```
Comment (goshawk-3) [inline pkg/gql/query/blocks.go:227]: If this is  the generator reward value, we should subtract the Dusk foundation reward as per `90% of the total value goes to the generator (rounded up)`

File: pkg/gql/query/blocks.go [hunk 2]
```diff
@@ -190,6 +190,31 @@ func resolveTxs(p graphql.ResolveParams) (interface{}, error) {
...
+		return uint64(4.8 * 1_000_000_000)
+	case blockHeight <= 50_000_000: // from 43_750_001 to 50_000_000 blocks emit 3.2 DUSK
+		return uint64(3.2 * 1_000_000_000)
+	case blockHeight <= 62_500_000: // from 50_000_001 to 62_500_000 blocks emit 1.6 DUSK
+		return uint64(1.6 * 1_000_000_000)
+	}
+	return uint64(0) // after 62_500_000 blocks emit 0 DUSK
+}
+
 func resolveReward(p graphql.ResolveParams) (interface{}, error) {
```
Comment (goshawk-3) [inline pkg/gql/query/blocks.go:218]: We should update graphql README to clarify if `reward` field is the total reward value or generator reward only.

**Review by goshawk-3 — CHANGES_REQUESTED** [review]

**Review by goshawk-3 — APPROVED** [review]
