### PR TITLE
Fix maintainer, split automaton into two

### LINKED ISSUE #481: Migrate maintainer to transaction provider
Maintainer still uses ristretto

### LINKED ISSUE #492: Split the automatons into StakeAutomaton and BidAutomaton
Currently the logic is inside the `maintainer` component

### PR DESCRIPTION
**Pull request by julesdesmit**
Fixes #481, fixes #492

### CODE REVIEW

File: pkg/core/consensus/bidautomaton/bidautomaton_test.go [hunk 1]
```diff
@@ -1 +1,80 @@
...
+	rpcBus := rpcbus.New()
+
+	m := bidautomaton.New(bus, rpcBus, nil)
+	_, err := m.AutomateConsensusTxs(context.Background(), &node.EmptyRequest{})
+	require.Nil(t, err)
+
+	return bus, rpcBus
+}
+
+func catchStakeRequest(t *testing.T, rb *rpcbus.RPCBus, respChan chan struct{}) {
```
Comment (autholykos) [inline pkg/core/consensus/bidautomaton/bidautomaton_test.go:73]: Avoid passing the testing context around. If there is an error in setting up the test, just panic (or return it if you are really interested in that). You are not testing the setup and therefore don't need to carry around a `testing.T`

Comment (julesdesmit) [reply pkg/core/consensus/bidautomaton/bidautomaton_test.go]: Done :)
