### PR TITLE
Integrate topics.Score propagation into Kadcast network

### LINKED ISSUE #1041: Integrate topics.Score message broadcast into Kadcast network
As per recent refactoring, Candidate block is now propagated as a payload item of `topics.Score` wire message. In addition, on recent TPS benchmark tests it turns out that the size of Candidate block has significant impact over average block time, respectively network TPS (see also #1019). Based on these findings, we need to integrate topics.Score message into Kadcast before comparing its Kadcast TPS capabilities to Gossip.

### LINKED ISSUE #1048: Alter selection phase so it broadcasts bestScore only
It  was found that a node is publishing  same` topics.Score` message twice when the score turns to be the highest one. This consensus message brings Candidate block which respectively has impact over consensus average time. An optimization here could be to publish only the best score as per the protocol specification.

This should be verified by test-harness reaching 10K rounds as a regression test.

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #1041 fixes #1048

### CODE REVIEW

File: pkg/core/consensus/selection/step.go [hunk 1]
```diff
@@ -142,17 +142,19 @@ func (p *Phase) Run(parentCtx context.Context, queue *consensus.Queue, evChan ch
...
 		}
 	}
 
 	for {
 		select {
 		case internalScoreResult := <-internalScoreChan:
-			p.collectScore(ctx, internalScoreResult.Payload().(message.Score))
+			// disable topics.Score network republish here as it's been already published in generateCandidate.
+			const republish = false
+			p.collectScore(ctx, internalScoreResult.Payload().(message.Score), internalScoreResult.Header(), republish)
```
Comment (julesdesmit) [inline pkg/core/consensus/selection/step.go:154]: As discussed before on the standup, I think it would be cleaner to remove the republishing in the candidate generator, and then avoid the boolean flag since we can always republish in `collectScore`. As checked with Toghrul, it's legal in the protocol to avoid republishing one's own `Score` message in case a better one was already processed.

**Review by julesdesmit — CHANGES_REQUESTED** [review]

File: pkg/core/consensus/selection/step.go (hunk 1 above)
Comment (goshawk-3) [reply pkg/core/consensus/selection/step.go:154]: Indeed. I should probably remove republish flag from this PR and handle the "optimization" with a separate issue/PR. This is because a such protocol-related change should pass 10K-round test to ensure no regressions occur. I still have a hunch that we had similar idea implemented time ago and that had negative impact on the consensus average time. Need to test this more.

Comment (goshawk-3) [reply pkg/core/consensus/selection/step.go]: @julesdesmit Feel free to review description of #1048

**Review by julesdesmit — APPROVED** [review]
LGTM
