### PR TITLE
Centralize consensus state into a single component

### LINKED ISSUE #11: Add more fine-grained logging to enhance debugging
Anything not covered by the monitoring system or current logging entries, should be added to get an as-complete-as-possible view of the node when problems arise.

### LINKED ISSUE #29: Subtract 1 DUSK when a node is extracted with deterministic sortition
The current version of deterministic sortition does not decrease the available stake of a node one or more DUSK of which has been already extracted for the committee. The deterministic sortition procedure has to be upgraded to subtract 1 DUSK from the stake available during an instance of sortition procedure when a DUSK under the control of the node is extracted for the committee.

### LINKED ISSUE #31: Implement multiple extraction from deterministic sortition
Currently a node can only be extracted from the committee once per step.

### LINKED ISSUE #72: Simplify `Reducer` algorithm by eliminating unnecessary asynchronous processing
This is somewhat related to #21 albeit more focused on a general simplification of the `Reducer` structure. 

The `Reducer` component is supposed to perform operations that are quite sequential in nature. A (grossly oversimplified) layout of its duty is the following loop:

- wait for a quorum of (valid) reduction events to be reached or a timeout to be triggered
- validate the winning candidate block
- propagate the 1st step reduction
- increment the step
- wait for a quorum of (valid) reduction events to be reached (or a timeout to be triggered)
- propagate the result

Such a layout might be better modeled with 2 separate `sync.WaitGroup` instead of overusing channels.

### LINKED ISSUE #95: Introduce component to centralize state changes
A `PhaseStore` component in change of state management would introduce the following benefits:
- solve the problem of excessive locking
- mitigate the risk of race conditions
- add consistency to the `Step` increment across consensus components
- clear duplicated code

 The `PhaseStore` would be loosely inspired by a `flux` architecture, where components are not allowed to modify a shared state (which would be kept immutable - by means of being passed by value) but can only request changes to be applied by a single source of truth.

The `PhaseStore` would be in charge of propagating the `RoundUpdate` to all components, forward results of other components after extracting (and propagating) the `Step`, filtering out obsolete messages (i.e. those with a `Round` or a `Step` in the past) and maintain a queue of future messages.

### LINKED ISSUE #106: Synchronizer is not capable of getting last block
After downloading first block, synchronizer stops downloading any other blocks due to timeout-ed error on getLastBlock call to Chain component.

```
level=debug msg="block received" our height=0 process=synchronizer received block height=1
level=trace msg="procedure started" process="accept block"
level=trace msg="procedure ended" process="accept block"
level=debug msg="block received" our height=1 process=synchronizer received block height=2
level=trace msg="procedure started" process="accept block"
level=error msg="problem handling message block" error="timeout-ed request" process=peer
```
On further investigation, it turns out that the Chain component is stuck at locking mutex:

```
sync.runtime_SemacquireMutex at sema.go:71
sync.(*RWMutex).RLock at rwmutex.go:50
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).Listen at chain.go:94
runtime.goexit at asm_amd64.s:1333
 - Async stack trace
main.Setup at server.go:51
```

### LINKED ISSUE #115: Race conditions detected on `make race` on consensus launching
```
WARNING: DATA RACE
Read at 0x00c00006e150 by goroutine 97:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*eventStopWatch).fetch()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/reducer.go:43 +0xbd
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*reducer).begin()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/reducer.go:105 +0x163

Previous write at 0x00c00006e150 by goroutine 37:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*reducer).startReduction()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/reducer.go:89 +0xef
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*broker).Listen()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/broker.go:86 +0x9c6

Goroutine 97 (running) created at:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*reducer).startReduction()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/reducer.go:100 +0x200
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*broker).Listen()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/broker.go:86 +0x9c6

Goroutine 37 (running) created at:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.Launch()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/broker.go:37 +0x358
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/factory.(*ConsensusFactory).StartConsensus()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/factory/factory.go:45 +0x234
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/initiator.startProvisioner()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/initiator/initiator.go:41 +0x1a4
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/initiator.LaunchConsensus()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/initiator/initiator.go:32 +0xab
==================
time="2019-10-07T14:04:18+03:00" level=info msg="Handling BidTx request" prefix=transactor
==================
WARNING: DATA RACE
Write at 0x00c0000365f0 by goroutine 37:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus.(*EventFilter).UpdateRound()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/eventfilter.go:97 +0x3c4
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*broker).Listen()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/broker.go:78 +0xd01

Previous read at 0x00c0000365f0 by goroutine 97:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*reducer).begin()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/reducer.go:105 +0x124

Goroutine 37 (running) created at:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.Launch()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/broker.go:37 +0x358
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/factory.(*ConsensusFactory).StartConsensus()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/factory/factory.go:45 +0x234
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/initiator.startProvisioner()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/initiator/initiator.go:41 +0x1a4
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/initiator.LaunchConsensus()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/initiator/initiator.go:32 +0xab

Goroutine 97 (running) created at:
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*reducer).startReduction()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/reducer.go:100 +0x200
  github.com/dusk-network/dusk-blockchain/pkg/core/consensus/reduction.(*broker).Listen()
      /mnt/hdd/repository/DuskNetwork/dusk-blockchain/pkg/core/consensus/reduction/broker.go:86 +0x9c6
==================

```

To enable non-WalletOnly mode
```diff
+++ b/pkg/core/consensus/maintainer/maintainer_test.go
@@ -36,7 +36,7 @@ func TestMain(m *testing.M) {
 
        bus = eventbus.New()
        rpcBus = rpcbus.New()
-       tr, err = transactor.New(bus, rpcBus, nil, nil, wallet.GenerateDecoys, wallet.GenerateInputs, true)
+       tr, err = transactor.New(bus, rpcBus, nil, nil, wallet.GenerateDecoys, wallet.GenerateInputs, false)
```

### LINKED ISSUE #127: Migrate components to the new state-centralized model
The consensus is now using a series of factories and round/step coordinator to remove fragmentation of state. Components like Agreement, Reducer, Generation and Selection needs to be adjusted to that model.
Depends on #95

### PR DESCRIPTION
**Pull request by julesdesmit**
Fixes #127, fixes #95, fixes #72, fixes #31, fixes #29, fixes #106, fixes #11, fixes #115

### CODE REVIEW

File: pkg/core/consensus/reduction/firststep/reducer.go [hunk 1]
```diff
@@ -161,11 +162,12 @@ func (r *Reducer) CollectBestScore(e consensus.Event) error {
...
 	step := r.eventPlayer.Forward(r.ID())
-	r.eventPlayer.Play(r.reductionID)
+	// `Play` dispatches queued events, so we should do this in a goroutine to avoid
+	// waiting too long to send a message.
+	go r.eventPlayer.Play(r.reductionID)
 
-	// sending reduction can very well be done concurrently
 	if r.handler.AmMember(r.round, step) {
-		go r.sendReduction(e.Header.BlockHash)
+		r.sendReduction(e.Header.BlockHash)
```
Comment (autholykos) [inline pkg/core/consensus/reduction/firststep/reducer.go]: While the issue is clear, there are a number of problems with your suggested solution. Apart from disliking goroutines as a tool to arbitrate instruction ordering, I see an even bigger "fixing through side effects" problem. If the issue is that queue flushing slows things down so much to impact the reduction message header, it would be better to fix that rather than introduce concurrency as a way to patch things up. In fact, I don't necessarily see a problem with the synchrony of queue flushing, as much as with these following:

```
...
// here the `round` is a state of the reducer and the `step` is local to this function and obtained by the EventPlayer/Coordinator
if r.handler.AmMember(r.round, step) {
    // in the following line, `sendReduction` calls `r.signer.Sign` which makes implicit use of the step and round the `Coordinator` is at
    // rather than the round and step of the line above
    r.sendReduction(e.Header.BlockHash) 
}
...
```

Comment (julesdesmit) [reply pkg/core/consensus/reduction/firststep/reducer.go]: I see your point. It's a very basic band-aid sort of fix, and the concurrency could be avoided as you point out. Do you suggest to construct the header within the `Reducer`, before passing it to the `Signer`?
