### PR TITLE
Reintroduce priority mapper in topics.Kadcast Collector

### LINKED ISSUE #1239: Re-enable sort-by-priority for kadcast outbound messages
**Describe the bug**
We should reintroduce priorities on ring buffer that collects Kadcast outbound messages.

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #1239

### CODE REVIEW

File: pkg/p2p/kadcast/writer.go [hunk 1]
```diff
@@ -55,26 +76,25 @@ func (w *Writer) Subscribe() {
...
-		}
-		// broadcast a message
-		if len(header) == 1 {
-			err = w.writeToAll(data, header, priority)
-		}
-		// log errors
-		if err != nil {
-			log.WithError(err).Warn("write failed")
-		}
-	}()
```
Comment (autholykos) [inline pkg/p2p/kadcast/writer.go:77]: I suppose removing the goroutine has to do with the fact that the `Consumer` already consumes the messages concurrently

**Review by autholykos — APPROVED** [review]
LGTM

**Review by herr-seppia — APPROVED** [review]

File: pkg/p2p/kadcast/writer.go (hunk 1 above)
Comment (goshawk-3) [reply pkg/p2p/kadcast/writer.go:77]: Both writeToAll/writeToPoint may block due to grpc client request they call. When this happens, runtime starts queue-ing goroutines. However our purpose with this PR is to queue messages in the Listener Ring buffer so that they are always sorted by priority/(type of topic).

If that makes sense to you @autholykos ?

Comment (autholykos) [reply pkg/p2p/kadcast/writer.go:77]: Yes it does
