### PR TITLE
Resolve any incompatibility between Rusk transaction schema and Dusk transaction schema

### LINKED ISSUE #1273: Incorporate rusk.VerifyTransaction into mempool
**Describe what you want implemented** 
On receiving a new transaction mempool does call  `proxy.VerifyTransaction` which has empty definition . `proxy.VerifyTransaction` should call rusk.VerifyTransaction.

NB: This is blocked until rusk provides rusk.VerifyTransaction and dusk-protobuf is updated.

### LINKED ISSUE #1274: Resolve any incompatibility between Rusk transaction schema and Dusk transaction schema
**Describe the bug**
Converting a Rusk transaction into Dusk Transaction and vice versa should be reviewed.

Functions to be reviewed:

- `transactions.MTransaction`
- `transactions.UTransaction`
- `transactions.MarshalTransactionPayload()`

In addition,

A list of pending (TODO) found in file `dusk-network/dusk-blockchain/pkg/core/data/ipc/transactions/transaction.go` should be taken into account (resolved) prior to Rusk integration.

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #1274 
fixes #1273

### CODE REVIEW

File: pkg/core/data/ipc/transactions/transaction.go [hunk 1]
```diff
@@ -25,28 +24,21 @@ const (
 	Tx TxType = iota
 	// Distribute indicates the coinbase and reward distribution contract call.
 	Distribute
```
Comment (herr-seppia) [inline pkg/core/data/ipc/transactions/transaction.go:26]: In rusk Distribute=0 and Transfer=1. Just make sure to handle it properly

File: pkg/core/mempool/mempool.go [hunk 2]
```diff
@@ -429,94 +424,6 @@ func (m Mempool) processGetMempoolTxsRequest(r rpcbus.Request) (interface{}, err
 	return outputTxs, err
 }
 
-// uType translates the node.TxType into transactions.TxType.
-func uType(t node.TxType) (transactions.TxType, error) {
```
Comment (herr-seppia) [inline pkg/core/mempool/mempool.go:433]: Should we still check the tx type? The ExecuteStateTransition return 2 different types

File: pkg/gql/query/blocks.go [hunk 3]
```diff
@@ -69,15 +68,7 @@ func newQueryBlock(b *block.Block) queryBlock {
...
-		_, fee := tx.Values()
-		feesPaid += fee
-
-		if tx.Type() == core.Distribute {
-			// TODO: this should align with the actual distribute tx structure
-			// once that is finalized.
-			r := binary.LittleEndian.Uint64(tx.StandardTx().CallData)
-			reward += r
-		}
+		feesPaid += tx.Fee()
```
Comment (herr-seppia) [inline pkg/gql/query/blocks.go:71]: This is not completely true. At the moment of writing, we are using GasLimit as indicator, later on we will' introduce GasSpent. The feesPaid should reflect the latter one

File: pkg/p2p/kadcast/peer_test.go [hunk 4]
```diff
@@ -80,7 +80,7 @@ func TestListenStreamReader(t *testing.T) {
 		b := m.Payload().(block.Block)
 		assert.True(m.Category() == topics.Block)
 		assert.True(b.Header.Height == 5525)
-		assert.True(len(b.Txs) == 12)
+		assert.True(len(b.Txs) == 11)
```
Comment (herr-seppia) [inline pkg/p2p/kadcast/peer_test.go:83]: Wut?

**Review by herr-seppia — COMMENTED** [review]
Comment inline, let's resolve them before approve

File: pkg/config/consts.go [hunk 5]
```diff
@@ -13,17 +13,14 @@ import (
...
 const (
 	// DUSK is one whole unit of DUSK.
-	DUSK = uint64(10000000000)
+	DUSK = uint64(1_000_000)
 
-	// GeneratorReward is the amount of Block generator default reward.
-	// TODO: TBD.
-	GeneratorReward = 50 * DUSK
+	// Default Block Gas limit.
+	BlockGasLimit = 1000 * DUSK
```
[the remark this answers is not in the document]
Comment (goshawk-3) [reply pkg/config/consts.go:19]: neither do I. That's why I raised a question in the chat but there was not particular answer. This should be documented properly and then I'll update this with another issue.

File: pkg/config/genesis/config.go [hunk 6]
```diff
@@ -8,55 +8,31 @@ package genesis
...
-
-	coinbaseAmount uint
+	Transactions []transactions.ContractCall
 }
 
 // NewConfig will construct a new genesis config. This function does sanity checks
 // on all passed parameters, and ensures a correct genesis block can be produced
 // from them.
-func NewConfig(timestamp int64, initialParticipants []PublicKey, committeeMembers [][]byte, initialCommitteeSize uint, seed []byte, stakeValue, coinbaseValue uint64, coinbaseAmount uint) (Config, error) {
+func NewConfig(timestamp int64, seed []byte, txs []transactions.ContractCall) (Config, error) {
```
[the remark this answers is not in the document]
Comment (goshawk-3) [reply pkg/config/genesis/config.go:27]: Yes, it is.

File: pkg/config/genesis/generation.go [hunk 7]
```diff
@@ -7,18 +7,20 @@
...
 	"github.com/dusk-network/dusk-blockchain/pkg/config"
 	"github.com/dusk-network/dusk-blockchain/pkg/core/data/block"
 	"github.com/dusk-network/dusk-blockchain/pkg/core/data/ipc/transactions"
-	"github.com/dusk-network/dusk-blockchain/pkg/p2p/wire/encoding"
 )
 
 // Generate a genesis block. The constitution of the block depends on the passed
 // config.
 func Generate(c Config) *block.Block {
+	// TODO: Populate this with real txs data from Rusk Transfer and Stake Contract
```
[the remark this answers is not in the document]
Comment (goshawk-3) [reply pkg/config/genesis/generation.go:18]: Not exactly. TODO here indicates that the question should be debated it's not relevant to current PR.

File: pkg/core/consensus/blockgenerator/candidate/blockgenerator.go [hunk 8]
```diff
@@ -47,14 +42,21 @@ type Generator interface {
...
+	if ct == 0 {
+		ct = 5
+	}
+
 	return &generator{
-		Emitter:   e,
-		executeFn: executeFn,
+		Emitter:     e,
+		executeFn:   executeFn,
+		callTimeout: time.Duration(ct) * time.Second,
```
[the remark this answers is not in the document]
Comment (goshawk-3) [reply pkg/core/consensus/blockgenerator/candidate/blockgenerator.go:59]: Not sure why you think this has been introduced now.  The rpcbus call timeout is there from day one. If you read the PR in depth you'll notice that this a minor change to avoid redundant timeout calculation on each rpcbus call.

File: pkg/core/mempool/mempool.go (hunk 2 above)
Comment (goshawk-3) [reply pkg/core/mempool/mempool.go:433]: Not sure what you mean. This `uType` was used only for converting  `node.TxType` (the one to be deprecated) to transactions.TxType. Nothing relevant here to ExecuteStateTransition.

File: pkg/gql/query/blocks.go (hunk 3 above)
Comment (goshawk-3) [reply pkg/gql/query/blocks.go:71]: Having in mind that `ExecutedTransaction` does not return `Fee`, feesPaid here will be always 0.

File: pkg/core/data/ipc/transactions/transaction.go (hunk 1 above)
Comment (goshawk-3) [reply pkg/core/data/ipc/transactions/transaction.go:26]: Please report an issue with reference to document or rust code file where this can be confirmed.

File: pkg/p2p/kadcast/peer_test.go (hunk 4 above)
Comment (goshawk-3) [reply pkg/p2p/kadcast/peer_test.go:83]: What do you mean by `Wut`? If you read the PR in depth, you'll notice that unit test ` TestListenStreamReader` uses createBlockMessage which calls `RandomBlock`. With this PR we remove `RandDistributeTx` from `RandomBlock` because it's only Rusk that knows how to generate it.
