### PR TITLE
Fix out of bounds error in sortition

### LINKED ISSUE #311: Out of bounds error observed during sortition
```
panic: runtime error: index out of range [5] with length 5

goroutine 1746 [running]:
github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user.Provisioners.MemberAt(0xc000e50f00, 0x5, 0x8, 0xc001fe73b0, 0x5, 0x81)
        /home/jules/go/src/github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user/provisioners.go:89 +0x118
github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user.Provisioners.extractCommitteeMember(0xc000e50f00, 0x5, 0x8, 0xc001fe73b0, 0x3c1632b17, 0x20,
0x0, 0x0)
        /home/jules/go/src/github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user/sortition.go:133 +0x9d
github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user.Provisioners.CreateVotingCommittee(0xc000e50f00, 0x5, 0x8, 0xc001fe73b0, 0x7, 0xc0007a8503, 0
x5, 0xc000e50f00, 0x5, 0x8, ...)
        /home/jules/go/src/github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user/sortition.go:108 +0x319
github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user.Provisioners.GenerateCommittees(0xc000e50f00, 0x5, 0x8, 0xc000127cb0, 0x7, 0x200308, 0x5, 0xc
0007a85f8, 0xa38a2f, 0xc0000950c8)
...
```

### PR DESCRIPTION
**Pull request by julesdesmit**
Fixes #311

### CODE REVIEW

**Comment by kieranhall** [comment]
# [Codecov](https://codecov.io/gh/dusk-network/dusk-blockchain/pull/312?src=pr&el=h1) Report
> Merging [#312](https://codecov.io/gh/dusk-network/dusk-blockchain/pull/312?src=pr&el=desc) into [master](https://codecov.io/gh/dusk-network/dusk-blockchain/commit/d68b0e10f2361acc603cf298ba2762a87fd80441&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/dusk-network/dusk-blockchain/pull/312?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #312   +/-   ##
=======================================
  Coverage   53.41%   53.41%           
=======================================
  Files         128      128           
  Lines        7185     7185           
=======================================
  Hits         3838     3838           
  Misses       2831     2831           
  Partials      516      516           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/dusk-network/dusk-blockchain/pull/312?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/dusk-network/dusk-blockchain/pull/312?src=pr&el=footer). Last update [d68b0e1...5910677](https://codecov.io/gh/dusk-network/dusk-blockchain/pull/312?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

File: pkg/core/consensus/user/sortition.go [hunk 1]
```diff
@@ -126,7 +126,7 @@ func (p Provisioners) CreateVotingCommittee(round uint64, step uint8, size int)
 func (p Provisioners) extractCommitteeMember(score uint64) []byte {
 	for i := 0; ; i++ {
 		// make sure we wrap around the provisioners array
-		if i >= len(p.Members) {
+		if i >= len(p.Set) {
```
Comment (ggoranov) [inline pkg/core/consensus/user/sortition.go]: Usually it's better to have this bound check in `MemberAt` returning error to avoid any panics on another use of the method.

Comment (julesdesmit) [reply pkg/core/consensus/user/sortition.go]: That's a good point. Will add it

Comment (autholykos) [reply pkg/core/consensus/user/sortition.go]: I too find more idiomatic if `MemberAt` actually returns an error when the client is asking for a member at an index inconsistent with the set size. It is up to the client to handle such error, rather than `MemberAt` to silently return the first member, which is an arbitrary result to the client's query

Comment (autholykos) [reply pkg/core/consensus/user/sortition.go]: I still think that the `extractCommitteeMember` should panic in case the handling fails (since it means that there are no members in the Committee, which should never happen)
