### PR TITLE
Fix createSortitionHash description

### LINKED ISSUE #1509: Fix createSortitionHash description
**Issue**
In `createSortitionHash`, the `i` parameter is indicated as _iteration number_, which sounds mistakenly related to the SA iterations. 

**Solution**
Fix description stating that  `i` is actually the number of the committee member being extracted.

### PR DESCRIPTION
**Pull request by fed-franz**
Resolves #1509

### CODE REVIEW

File: pkg/core/consensus/user/sortition.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ func (v VotingCommittee) MarshalJSON() ([]byte, error) {
 	return json.Marshal(data)
 }
 
-// createSortitionHash takes Seed value 'seed', round number 'round', step number 'step', and iteration number 'i',
+// createSortitionHash takes Seed value 'seed', round number 'round', step number 'step', and committee member number 'i',
```
Comment (herr-seppia) [inline pkg/core/consensus/user/sortition.go:80]: What about index `instead` of `number`?
```suggestion
// createSortitionHash takes Seed value 'seed', round number 'round', step number 'step', and committee member index 'i',
```

Comment (fed-franz) [reply pkg/core/consensus/user/sortition.go:80]: I wasn't convinced by index, because it can be confused with the index of the member in the provisioner list,
but I guess conceptually it's correct to consider 'i' as the index in the committee that has to be "filled in" with a new member (i.e. the one we're extracting now).

Maybe we could say it explicitly. Like:
"..., and the index 'i' of the committee member to be extracted." ?

Comment (herr-seppia) [reply pkg/core/consensus/user/sortition.go:80]: Yes, let's go for the explicitness

**Review by herr-seppia — APPROVED** [review]
LGTM
