### PR TITLE
Terminate gracefully all subsystems/components and pending grpc requests

### LINKED ISSUE #1241: Implement graceful shutdown for components
**Describe the bug**
On recent review, It was noticed that dusk.Server does not cancel the context passed to Mempool, Chain and GRPC clients.

**Expected behaviour**
On calling `func (s *Server) Close()`,  cancelling the Parent(Server) context is a must. Also, we could revise if Parent Context can be used for closing other components instead of explicit `Close` call.

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #1241 

- Cancel all goroutine loops (kadcast listener, consensus, mempool, chain, gossip read loop)
- Close non-cancelable components (db driver, gql server, eventbus)
- Cancel pending grpc client requests on state/network services.

### CODE REVIEW

File: cmd/dusk/server.go [hunk 1]
```diff
@@ -299,16 +315,36 @@ func Setup() *Server {
...
+	// Close graphql server.
+	if s.gqlServer != nil {
+		if err := s.gqlServer.Close(); err != nil {
+			log.WithError(err).Warn("failed to close gql server")
+		}
+	}
+
+	if s.grpcServer != nil {
+		s.grpcServer.GracefulStop()
+	}
```
Comment (autholykos) [inline cmd/dusk/server.go:330]: Does the golang process still need to serve any data over gRPC?

File: cmd/dusk/server.go [hunk 2]
```diff
@@ -299,16 +315,36 @@ func Setup() *Server {
...
 	}
+
+	if s.dbDriver != nil {
+		if err := s.dbDriver.Close(); err != nil {
+			log.WithError(err).Warn("failed to close db driver")
+		}
+	}
+
+	s.rpcBus.Close()
+	s.eventBus.Close()
```
Comment (autholykos) [inline cmd/dusk/server.go:347]: Some of these closures should be done in parallel using a `WaitGroup` to speed up the teardown process

**Review by autholykos — APPROVED** [review]
There are some minor leftovers for `Server` termination to be tackled by other issues. LGTM

**Review by herr-seppia — APPROVED** [review]

File: cmd/dusk/server.go (hunk 1 above)
Comment (goshawk-3) [reply cmd/dusk/server.go:330]: It's going to be removed on merging testnet branch. For now we need gRPC for maintaining healthy test-harness. Test-harness pushes stake and transfer transactions via grpc.
