### PR TITLE
Fix reward and feesPaid in graphQL

### LINKED ISSUE #1314: Wrong block info from GraphQL
Values of Reward and FeesPaid are always 0

### PR DESCRIPTION
**Pull request by herr-seppia**
Resolves #1314

### CODE REVIEW

File: pkg/gql/query/blocks.go [hunk 1]
```diff
@@ -207,10 +187,76 @@ func resolveTxs(p graphql.ResolveParams) (interface{}, error) {
...
+		// Retrieve DB conn from context
+		db, ok := p.Context.Value("database").(database.DB)
+		if !ok {
+			return nil, errors.New("context does not store database conn")
+		}
+
+		reward := uint64(0)
+
+		err := db.View(func(t database.Transaction) error {
+			fetched, err := t.FetchBlockTxs(b.Hash)
```
Comment (goshawk-3) [inline pkg/gql/query/blocks.go:205]: Any reason to fetch txs from database as you have them already in `b.Txs`?

```
for _, tx := range b.Txs {
...
```

Comment (herr-seppia) [reply pkg/gql/query/blocks.go:205]: During the resolve of this graphql node, the transactions are not resolved yet, so they are not valued (this was the issue that this PR is going to solve)

File: pkg/gql/query/types.go [hunk 2]
```diff
@@ -60,10 +60,12 @@ var Header = graphql.NewObject(
 				Type: UnixTimestamp,
 			},
 			"reward": &graphql.Field{
-				Type: graphql.Int,
+				Type:    graphql.Float,
+				Resolve: resolveReward,
 			},
 			"feespaid": &graphql.Field{
```
Comment (goshawk-3) [inline pkg/gql/query/types.go:66]: Getting `feespaid` per transactions fails:

```
./transaction.sh 9501 8cad3e5ff99e86ab14702f9987813f7dd7f7052df136696e0d251ceb261ebd07
9501  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   369  100   134  100   235   130k   229k --:--:-- --:--:-- --:--:--  360k
{
    "data": null,
    "errors": [
        {
            "message": "Cannot query field \"feespaid\" on type \"Transaction\".",
            "locations": [
                {
                    "line": 1,
                    "column": 148
                }
            ]
        }
    ]

```

Comment (herr-seppia) [reply pkg/gql/query/types.go:66]: FeesPaid in transaction has been removed in favor of GasSpent.

It can be easily calculated at clientSide as GasSpent*GasPrice

Comment (goshawk-3) [reply pkg/gql/query/types.go:66]: Awesome!

**Review by goshawk-3 — APPROVED** [review]
