### PR TITLE
Remove potential panic on closed channel send when connection drops

### LINKED ISSUE #1020: Remove send on closed channel
In the devnet, the following error was observed after some of the nodes panicked:

```
panic: send on closed channel

goroutine 128 [running]:
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.sendError(0xc0023f9140, 0x108c640, 0xc01fa7b310)
        /work/pkg/p2p/peer/peer.go:211 +0x49
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*Writer).writeLoop(0xc002231110, 0x10a2c40, 0xc00245ac00, 0xc0023f9080, 0xc0023f9140)
        /work/pkg/p2p/peer/peer.go:295 +0x650
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*Writer).Serve(0xc002231110, 0x10a2c40, 0xc00245ac00, 0xc0023f9080, 0xc0023f9140)
        /work/pkg/p2p/peer/peer.go:225 +0xd8
created by github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.Create
        /work/pkg/p2p/peer/peer.go:202 +0x106
```

This is accompanied by the logs showing that some connections are dropped:

```
{"error":"write tcp 159.89.24.209:58020-\u003e165.227.33.253:7100: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:47Z"}
{"coordinator_round":45145,"level":"debug","msg":"storing future round for later","process":"agreement","round":45147,"time":"2021-04-16T14:29:53Z","topic":"Agreement"}
{"error":"write tcp 159.89.24.209:60666-\u003e104.131.173.173:7100: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:54Z"}
{"error":"write tcp 159.89.24.209:7100-\u003e143.110.156.197:55554: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:55Z"}
{"coordinator_round":45145,"level":"debug","msg":"storing future round for later","process":"agreement","round":45148,"time":"2021-04-16T14:30:11Z","topic":"Agreement"}
{"coordinator_round":45145,"level":"debug","msg":"storing future round for later","process":"agreement","round":45146,"time":"2021-04-16T14:30:11Z","topic":"Agreement"}
{"error":"read tcp 159.89.24.209:38204-\u003e46.101.134.69:7100: i/o timeout","level":"warning","msg":"error reading message","process":"peer","time":"2021-04-16T14:29:58Z"}
{"error":"read tcp 159.89.24.209:38204-\u003e46.101.134.69:7100: i/o timeout","level":"warning","msg":"error received from peer","process":"server","time":"2021-04-16T14:30:11Z"}
{"error":"write tcp 159.89.24.209:7100-\u003e134.122.34.54:50876: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:58Z"}
{"error":"write tcp 159.89.24.209:55820-\u003e165.227.237.8:7100: write: broken pipe","level":"error","msg":"got error back from keepAlive","process":"keepaliveloop","time":"2021-04-16T14:29:58Z"}
{"error":"write tcp 159.89.24.209:38204-\u003e46.101.134.69:7100: write: broken pipe","level":"warning","msg":"error writing message","process":"writeloop","time":"2021-04-16T14:29:58Z"}
```

Right after these entries, the logs indicate a new startup.

### PR DESCRIPTION
**Pull request by julesdesmit**
This is achieved by fully removing the errChan
and substituting it for another Context object, created
when the peer is started up. The cancellation of one
of the loops will cascade a cancellation in the other,
without any risk of panicking.

Fixes #1020

### CODE REVIEW

File: pkg/p2p/peer/peer.go [hunk 1]
```diff
@@ -194,35 +194,30 @@ func (p *Reader) Accept() error {
 // Create two-way communication with a peer. This function will allow both
 // goroutines to run as long as no errors are encountered. Once the first error
 // comes through, the context is canceled, and both goroutines are cleaned up.
```
Comment (autholykos) [inline pkg/p2p/peer/peer.go:196]: This comment is no longer relevant. There is no visible error being thrown nor handled directly by `Create`

**Review by autholykos — CHANGES_REQUESTED** [review]
Just a small comment update. Afterwards, I think this PR can be merged. However, in the grand scheme of things, I don't particularly like the idea of letting the writer and the reader handle the error blindly. In some cases, we might want to bubble the error up and let the server decide what to do depending on the error detected. 

There should be a way to do it without triggering a close channel panic. This can be achieved by wrapping the channel into a specialized `SafeChannel` struct that contains the channel, a `sync.Once` (or a mutex) to close the channel and a boolean to keep track of channel closure.

**Comment by julesdesmit** [comment]
> Just a small comment update. Afterwards, I think this PR can be merged. However, in the grand scheme of things, I don't particularly like the idea of letting the writer and the reader handle the error blindly. In some cases, we might want to bubble the error up and let the server decide what to do depending on the error detected.

I figured that in most cases, the peer just ends up killing its own goroutines, so that's why I wasn't too bothered about bubbling stuff back up. In any case, I will extrapolate this into an issue for further discussion and a potential refactor.
