### PR TITLE
Retry random key generation, in case of EOF

### LINKED ISSUE #44: Fix intermittent failure of BLS keypair generation
When calling `user.NewRandKeys` or `user.NewKeysFromBytes`, if the `rand.Reader`, or any other seed, runs out of bytes before being able to generate a BLS keypair, it returns an EOF error. This can be easily mitigated by adding some logic to retry with a new seed in this case. Additionally, this should take care of an intermittently failing test.

### PR DESCRIPTION
**Pull request by julesdesmit**
Fixes #44

### CODE REVIEW

File: pkg/core/consensus/user/keys.go [hunk 1]
```diff
@@ -21,7 +21,12 @@ type Keys struct {
 // NewRandKeys will generate and return new bls and ed25519
 // keys to be used in consensus
 func NewRandKeys() (Keys, error) {
-	return NewKeysFromReader(nil)
+	keys, err := NewKeysFromReader(nil)
+	if err == io.EOF {
+		return NewRandKeys()
```
Comment (ggoranov) [inline pkg/core/consensus/user/keys.go]: Is there a reason for using recursion instead of a simple loop here?

Comment (julesdesmit) [reply pkg/core/consensus/user/keys.go]: It's more concise, I think. Other than that, no reason.

Comment (autholykos) [reply pkg/core/consensus/user/keys.go]: In general I would avoid recursion. In this case though, recursion helps the conciseness and I find it more elegant than a 'for' with a nested if. At the end of the day the recursion is a rare circumstance while a 'for' would suggest that an EOF is expected to happen less infrequently

Comment (ggoranov) [reply pkg/core/consensus/user/keys.go]: My point was this would grow the stack indefinitely. If a `for` was used the compiler would choose to simply inline `NewRandKeys`

Comment (autholykos) [reply pkg/core/consensus/user/keys.go]: Only if the recursion actually happens, which is a rare occurrence. However, point taken. Feel free to revert to a for loop
